### ISSUE TITLE
Request Demo

### ISSUE THREAD

**Issue by MarkusLange** [skpang/Teensy32_LIN-bus_NCV7430_RGB_demo#1]
Did you have an NCV7430 request Demo?

With communication between Master and Slave.

**Comment by skpang** [comment]
Not for the NCV7430 but there is one for the Microchip APGRD004.
https://github.com/skpang/Teensy32_LIN-bus_master_request_demo/blob/master/Teensy32_LIN-bus_master_request_demo.ino

**Comment by MarkusLange** [comment]
Yes I have seen it, but I was looking for one for the NCV7430, I want to see inside the Status Register.
